// Run with PGLITE_MODULE pointing to a temporary @electric-sql/pglite installation.
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const pg = new PGlite();
await pg.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
CREATE TABLE users(id BIGINT PRIMARY KEY); INSERT INTO users SELECT generate_series(1,9);
GRANT ALL ON users TO service_role;`);
await pg.exec(await readFile(new URL('../migration_v9.sql', import.meta.url), 'utf8'));
const id = n => `00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const call = async (actor, action, args={}) => (await pg.query('SELECT identity_action($1,$2,$3::jsonb) AS result',[actor,action,JSON.stringify(args)])).rows[0].result;
for (const role of ['anon','authenticated']) {
  await pg.exec(`SET ROLE ${role}`);
  await assert.rejects(pg.query('SELECT * FROM employee_links'), /permission denied/);
  await assert.rejects(call(1,'create',{id:id(1),name:'Test'}), /permission denied/);
  await pg.exec('RESET ROLE');
}
await pg.exec('SET ROLE service_role');
await call(1,'create',{id:id(1),name:'Restaurant A'});
await call(2,'create',{id:id(2),name:'Restaurant B'});
assert.equal((await call(1,'create',{id:id(9),name:'Duplicate'})).id,id(1));
await assert.rejects(call(3,'invite',{hash:'stolen'}), /identity_forbidden/);
await call(1,'invite',{hash:'first'});
await call(2,'invite',{hash:'other'});
const req = (uid,n,key,hash='first') => call(uid,'request',{id:id(n),hash,name:key,name_key:key});
await assert.rejects(req(3,10,'Alex','invalid'), /identity_invite_expired/);
await req(3,10,'alex');
await assert.rejects(call(2,'approve',{id:id(10)}), /identity_stale/);
await assert.rejects(call(3,'approve',{id:id(10)}), /identity_forbidden/);
await call(1,'approve',{id:id(10)});
assert.equal((await req(3,11,'alex')).id,id(10));
await req(4,12,'alex');
await assert.rejects(call(1,'approve',{id:id(12)}), /duplicate key/);
await assert.rejects(req(3,13,'alex','other'), /identity_other_restaurant/);
await req(3,14,'new name');
await assert.rejects(call(1,'approve',{id:id(10)}), /identity_stale/);
await assert.rejects(call(3,'leave',{id:id(10)}), /identity_stale/);
await call(1,'approve',{id:id(14)});
await call(1,'revoke',{id:id(14)});
await assert.rejects(call(1,'revoke',{id:id(14)}), /identity_stale/);
await call(1,'reject',{id:id(12)});
await call(1,'invite',{hash:'rotated'});
await assert.rejects(req(5,15,'third'), /identity_invite_expired/);
await req(5,15,'same','rotated');await req(6,16,'same','rotated');
const concurrent = await Promise.allSettled([call(1,'approve',{id:id(15)}),call(1,'approve',{id:id(16)})]);
assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);
await pg.exec(`UPDATE restaurants SET invite_expires_at=now()-interval '1 second' WHERE id='${id(1)}'`);
await assert.rejects(req(7,17,'expired','rotated'), /identity_invite_expired/);
await call(1,'invite',{hash:'active'});
await pg.exec('DELETE FROM users WHERE id=3');
assert.equal((await pg.query('SELECT * FROM employee_links WHERE user_id=3')).rows.length,0);
await pg.exec('DELETE FROM users WHERE id=1');
await assert.rejects(req(7,17,'orphan','active'), /identity_invite_expired/);
await call(5,'leave',{id:id(15)});
assert.equal((await pg.query('SELECT * FROM employee_links WHERE user_id=5')).rows.length,0);
await pg.close();
console.log('Identity SQL checks passed: roles, isolation, approval, collisions, stale actions, rotation, expiry, deletion.');
